(function(){'use strict';
const style=document.createElement('style');style.textContent=`
:focus-visible{outline:2px solid var(--accent-cyan,#67e8f9)!important;outline-offset:3px}
button,input,select,textarea{font:inherit} .omni-sync-select label{min-height:36px;display:inline-flex;align-items:center;gap:6px}
[data-password-editor] label{display:block;margin:12px 0 6px}[data-password-editor] input,[data-password-editor] textarea{width:100%}
.sb-indeterminate{animation:sb-transfer 1.3s ease-in-out infinite alternate}@keyframes sb-transfer{to{transform:translateX(180%)}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;scroll-behavior:auto!important;transition:none!important}}
@media(max-width:760px){.btn,.icon-btn{min-height:44px}input,select,textarea{font-size:16px!important}.omni-sync-modal{max-height:92dvh;overflow:auto}}
#view-today .v56-daily-grid{display:none}#view-today .v56-daily-head{padding:10px 14px}
.sb-recovery-tools{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}
`;document.head.append(style);
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function conflicts(){const rows=SecondBrainSync.conflicts();const o=document.createElement('div');o.className='modal-overlay active';o.innerHTML='<section class="modal" role="dialog" aria-modal="true" aria-label="Sync alternatives"><div class="modal-header"><h3>Retained sync alternatives</h3><button class="icon-btn" data-close aria-label="Close">×</button></div><div class="modal-body"><p>Different values received from another device are retained here for review. Export these alternatives before making corrections in the relevant page.</p>'+ (rows.length?rows.map(r=>'<details><summary>'+E(JSON.parse(r.path).join(' › '))+'</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere">'+E(JSON.stringify(r.values.map(v=>v.node?.value),null,2))+'</pre></details>').join(''):'<p>No retained alternatives.</p>')+'<button class="btn" data-export>Export alternatives</button></div></section>';document.body.append(o);o.querySelector('[data-close]').onclick=()=>o.remove();o.querySelector('[data-export]').onclick=()=>download('SecondBrain_SyncAlternatives.json',rows)}
function addTools(){const exportBtn=document.getElementById('v35-db-export');if(!exportBtn||document.getElementById('sb-recovery-tools'))return;const box=document.createElement('div');box.id='sb-recovery-tools';box.className='sb-recovery-tools';box.innerHTML='<button class="btn" data-conflicts>Review sync alternatives</button><button class="btn" data-diagnostics>Export diagnostics</button>';exportBtn.closest('.v35-card')?.append(box);box.querySelector('[data-conflicts]').onclick=conflicts;box.querySelector('[data-diagnostics]').onclick=async()=>{let quota;try{quota=await navigator.storage?.estimate()}catch(_){}download('SecondBrain_Diagnostics.json',{version:2,at:new Date().toISOString(),online:navigator.onLine,secureContext:isSecureContext,storage:quota,recordCounts:Object.fromEntries(Object.entries(state).filter(([,v])=>Array.isArray(v)).map(([k,v])=>[k,v.length])),retainedAlternatives:SecondBrainSync.conflicts().length})}}
let pending=false;const base=window.renderAll;if(base)window.renderAll=function(){const result=base.apply(this,arguments);if(!pending){pending=true;requestAnimationFrame(()=>{pending=false;addTools()})}return result};
document.addEventListener('secondbrain:transfer',e=>{const d=e.detail;document.querySelectorAll('[data-local-progress-text]').forEach(el=>el.textContent=`Receiving ${Math.round(d.received/1024)} / ${Math.round(d.total/1024)} KB`)});
document.addEventListener('click',e=>{if(e.target.closest('[data-sb-disconnect]')){SecondBrainSync.disconnect();e.target.closest('.omni-sync-overlay')?.remove()}requestAnimationFrame(addTools)});addTools();
})();
