import {test} from 'node:test';import assert from 'node:assert/strict';import '../js/data-core.js';
const D=globalThis.SecondBrainData;
function edit(base,next,id){return D.capture(D.initialize(base),base,next,id)}
test('independent nested edits survive both merge directions',()=>{const base={life:{people:[],projects:[]}};const a=edit(base,{life:{people:[{id:'p',name:'Alice'}],projects:[]}},'a'),b=edit(base,{life:{people:[],projects:[{id:'q',name:'Study'}]}},'b');for(const [x,y]of [[a,b],[b,a]]){const d=D.merge(x,y).document;assert.equal(d.life.people[0].name,'Alice');assert.equal(d.life.projects[0].name,'Study')}});
test('independent days on same habit survive',()=>{const base={habits:[{id:'h',log:{}}]};const a=edit(base,{habits:[{id:'h',log:{mon:true}}]},'a'),b=edit(base,{habits:[{id:'h',log:{tue:true}}]},'b');assert.deepEqual(D.merge(a,b).document.habits[0].log,{mon:true,tue:true})});
test('deletion metadata persists and stale third device cannot resurrect',()=>{const base={notes:[{id:'n',title:'old'}]},a=edit(base,{notes:[]},'a'),b=D.initialize(base);const merged=D.merge(b,a);assert.deepEqual(merged.document.notes,[]);assert.deepEqual(D.merge(merged.meta,b).document.notes,[])});
test('same-field conflict is deterministic and retained',()=>{const base={note:'start'},a=edit(base,{note:'A'},'a'),b=edit(base,{note:'B'},'b');assert.equal(D.merge(a,b).document.note,D.merge(b,a).document.note);assert.ok(D.merge(a,b).meta.conflicts.length)});
test('logical revisions do not depend on wall clock',()=>{const base={value:1};const a=edit(base,{value:2},'a');const next=D.capture(a,{value:2},{value:3},'b');assert.equal(D.merge(a,next).document.value,3)});
test('device identities and snapshots are excluded from auxiliary data',()=>{for(const k of ['omnios_push_device_v1','omnios_push_token_v2','omnios_sync_pairs_v1','omnios_local_answer_abc','omnios_app_snapshot_slot_v1'])assert.equal(D.userAux(k),false);assert.equal(D.userAux('omnios_bible_v571'),true)});
test('scope excludes credentials and unrelated modules',()=>{const m=D.initialize({entries:[{id:'t'}],notes:[{id:'n'}],passwords:[{id:'p',password:'secret'}]});const s=D.select(m,['tasks']);assert.equal(JSON.stringify(s).includes('secret'),false);assert.equal(D.materialize(s.entries).notes,undefined);assert.equal(D.materialize(s.entries).entries.length,1)});
test('prototype pollution is rejected',()=>{assert.throws(()=>D.merge(D.initialize({}),{version:2,entries:{'["__proto__","x"]':{rev:[1,'evil'],node:{kind:'value',value:true}}}}));assert.equal({}.x,undefined)});
